FROM node:18-alpine

WORKDIR /app

# Instalar dependências de desenvolvimento
COPY package*.json ./
RUN npm install

# Copiar o código fonte
COPY . .

# Expor a porta
EXPOSE 3000

# Comando para iniciar em modo de desenvolvimento
CMD ["npm", "run", "dev"]

